language:
	php

php:
	- 5.3
	- 5.4

before_script:
	- curl -s http://getcomposer.org/installer | php
	- php composer.phar update -v

script:
	- phpunit --coverage-text --configuration assignment_01-2/Tests/Conf/phpunit.xml